name: "Tox21_p53"
url: "https://ls11-www.cs.uni-dortmund.de/people/morris/graphkerneldatasets/Tox21_p53.zip"
attributes:
  undirected: true
  has_graphlabels: true
  has_nodelabels: true
  has_edgelabels: true
  has_nodeattrs: false
  has_edgeattrs: false